import { Upgrade } from "../types";

export const upgrades: Upgrade[] = [
  // Tier 1 - Basic Pleasures (100 dopamine) - Single Benefits
  {
    name: "Fidget Toy",
    description: "Satisfying clicks and tactile feedback",
    cost: 10,
    dopaminePerClick: 1,
    dopaminePerSecond: 0,
    currencyPerClick: 0,
    currencyPerSecond: 0,
    unlock: 100,
  },
  {
    name: "Energy Drink",
    description: "Quick bursts of energy and focus",
    cost: 25,
    dopaminePerClick: 2,
    dopaminePerSecond: 0,
    currencyPerClick: 0,
    currencyPerSecond: 0,
    unlock: 200,
  },
  {
    name: "Task Planner",
    description: "Organize your work efficiently",
    cost: 20,
    dopaminePerClick: 0,
    dopaminePerSecond: 0,
    currencyPerClick: 1,
    currencyPerSecond: 0,
    unlock: 100,
  },
  {
    name: "Comfy Chair",
    description: "Continuous comfort throughout the day",
    cost: 15,
    dopaminePerClick: 0,
    dopaminePerSecond: 1,
    currencyPerClick: 0,
    currencyPerSecond: 0,
    unlock: 100,
  },
  {
    name: "Ambient Music",
    description: "Soothing background tunes",
    cost: 30,
    dopaminePerClick: 0,
    dopaminePerSecond: 2,
    currencyPerClick: 0,
    currencyPerSecond: 0,
    unlock: 200,
  },
  {
    name: "Productivity Timer",
    description: "Track and optimize your work sessions",
    cost: 25,
    dopaminePerClick: 0,
    dopaminePerSecond: 0,
    currencyPerClick: 0,
    currencyPerSecond: 1,
    unlock: 100,
  },
  // Tier 2 (200 dopamine) - Single Benefits with Higher Values
  {
    name: "Chocolate Bar",
    description: "Sweet, sweet endorphins",
    cost: 50,
    dopaminePerClick: 4,
    dopaminePerSecond: 0,
    currencyPerClick: 0,
    currencyPerSecond: 0,
    unlock: 200,
  },
  {
    name: "Skill Course",
    description: "Learn valuable new abilities",
    cost: 60,
    dopaminePerClick: 0,
    dopaminePerSecond: 0,
    currencyPerClick: 4,
    currencyPerSecond: 0,
    unlock: 200,
  },
  // Tier 3 (400 dopamine) - Dual Benefits Begin
  {
    name: "Favorite Song",
    description: "Music that hits all the right notes",
    cost: 100,
    dopaminePerClick: 8,
    dopaminePerSecond: 4,
    currencyPerClick: 0,
    currencyPerSecond: 0,
    unlock: 400,
  },
  {
    name: "Side Project",
    description: "Extra income from your passion project",
    cost: 120,
    dopaminePerClick: 0,
    dopaminePerSecond: 0,
    currencyPerClick: 8,
    currencyPerSecond: 4,
    unlock: 400,
  },
  // Tier 4 (800 dopamine)
  {
    name: "Exercise High",
    description: "Natural endorphins from a good workout",
    cost: 250,
    dopaminePerClick: 16,
    dopaminePerSecond: 8,
    currencyPerClick: 0,
    currencyPerSecond: 0,
    unlock: 800,
  },
  {
    name: "Freelance Gig",
    description: "Profitable independent work",
    cost: 300,
    dopaminePerClick: 0,
    dopaminePerSecond: 0,
    currencyPerClick: 16,
    currencyPerSecond: 8,
    unlock: 800,
  },
  // Tier 5 (1,600 dopamine)
  {
    name: "Gaming Victory",
    description: "The thrill of winning a match",
    cost: 500,
    dopaminePerClick: 32,
    dopaminePerSecond: 16,
    currencyPerClick: 0,
    currencyPerSecond: 0,
    unlock: 1600,
  },
  {
    name: "Investment Portfolio",
    description: "Smart money management pays off",
    cost: 600,
    dopaminePerClick: 0,
    dopaminePerSecond: 0,
    currencyPerClick: 32,
    currencyPerSecond: 16,
    unlock: 1600,
  },
  // Tier 6 (3,200 dopamine)
  {
    name: "Job Promotion",
    description: "Career advancement feels amazing",
    cost: 1000,
    dopaminePerClick: 64,
    dopaminePerSecond: 32,
    currencyPerClick: 0,
    currencyPerSecond: 0,
    unlock: 3200,
  },
  {
    name: "Business Venture",
    description: "Your own successful enterprise",
    cost: 1200,
    dopaminePerClick: 0,
    dopaminePerSecond: 0,
    currencyPerClick: 64,
    currencyPerSecond: 32,
    unlock: 3200,
  },
  // Tier 7 (6,400 dopamine)
  {
    name: "Dream Vacation",
    description: "Paradise found and memories made",
    cost: 2500,
    dopaminePerClick: 128,
    dopaminePerSecond: 64,
    currencyPerClick: 0,
    currencyPerSecond: 0,
    unlock: 6400,
  },
  {
    name: "Tech Startup",
    description: "Innovative solution with high returns",
    cost: 3000,
    dopaminePerClick: 0,
    dopaminePerSecond: 0,
    currencyPerClick: 128,
    currencyPerSecond: 64,
    unlock: 6400,
  },
  // Tier 8 (12,800 dopamine)
  {
    name: "Life Goal Achievement",
    description: "Accomplishing something truly meaningful",
    cost: 5000,
    dopaminePerClick: 256,
    dopaminePerSecond: 128,
    currencyPerClick: 0,
    currencyPerSecond: 0,
    unlock: 12800,
  },
  {
    name: "Global Enterprise",
    description: "International business success",
    cost: 6000,
    dopaminePerClick: 0,
    dopaminePerSecond: 0,
    currencyPerClick: 256,
    currencyPerSecond: 128,
    unlock: 12800,
  },
  // Tier 9 (25,600 dopamine)
  {
    name: "True Love",
    description: "Finding your soulmate",
    cost: 10000,
    dopaminePerClick: 512,
    dopaminePerSecond: 256,
    currencyPerClick: 0,
    currencyPerSecond: 0,
    unlock: 25600,
  },
  {
    name: "Market Revolution",
    description: "Disrupting entire industries",
    cost: 12000,
    dopaminePerClick: 0,
    dopaminePerSecond: 0,
    currencyPerClick: 512,
    currencyPerSecond: 256,
    unlock: 25600,
  },
  // Tier 10 (51,200 dopamine)
  {
    name: "World Changing Discovery",
    description: "Contributing something revolutionary to humanity",
    cost: 25000,
    dopaminePerClick: 1024,
    dopaminePerSecond: 512,
    currencyPerClick: 0,
    currencyPerSecond: 0,
    unlock: 51200,
  },
  {
    name: "Economic Empire",
    description: "Reshape the global economy",
    cost: 30000,
    dopaminePerClick: 0,
    dopaminePerSecond: 0,
    currencyPerClick: 1024,
    currencyPerSecond: 512,
    unlock: 51200,
  },
];
